services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /media/rshah17/Drive\ 2/Audiobooks:/audiobooks
      - /media/rshah17/Drive\ 2/Podcasts:/podcasts
      - ./metadata:/metadata
      - ./config:/config
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - /media/rshah17/Drive\ 11/Jellyfin/config:/config
      - /media/rshah17/Drive\ 11/Jellyfin/cache:/cache
      - type: bind
        source: '/media/rshah17/Drive 11/Watchable_Media/'
        target: /media
        read_only: true
    restart: 'unless-stopped' 
