services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: tailscale-nginx
    ports:
      - 8096:8096
      - 13378:80
      - "4533:4533"
      - 8000:8000
      - 8409:8409
      - 80:8080
      - 5432:5432
    environment:
      - TS_AUTHKEY=tskey-auth-kei1hw1sMY11CNTRL-UmM1CyaUi83yw8esGxpq83yvAf9JHq9G
      - TS_EXTRA_ARGS=--advertise-tags=tag:server
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    network_mode: service:tailscale
    volumes:
      - "/media/rshah17/Drive 2/Audiobooks:/audiobooks"
      - "/media/rshah17/Drive 2/Podcasts:/podcasts"
      - ./metadata:/metadata
      - "/media/rshah17/Drive 2/Audiobookshelf_config:/config"
    restart: 'unless-stopped'
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: service:tailscale
    volumes:
      - "/media/rshah17/Drive 1/Jellyfin/config:/config"
      - "/media/rshah17/Drive 1/Jellyfin/cache:/cache"
      - type: bind
        source: "/media/rshah17/Drive 1/Watchable_Media/"
        target: /media
        read_only: true
    restart: 'unless-stopped'
  navidrome:
    image: deluan/navidrome:latest
    restart: unless-stopped
    network_mode: service:tailscale
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/media/rshah17/Drive 3/Music_data:/data"
      - "/media/rshah17/Drive 3/Music:/music:ro"
  miniflux:
    image: miniflux/miniflux:latest
    network_mode: service:tailscale
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:145rss@localhost/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=145rss
      - POSTGRES_DB=miniflux
    network_mode: service:tailscale
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
volumes:
  miniflux-db:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/rshah17/Drive 2/db'
        #ersatz_tv:
        #  image: jasongdove/ersatztv
        #   container_name: ersatztv
        #   network_mode: service:tailscale
        # volumes:
        #- "/media/rshah17/Drive 1/ersatz_config/:/root/.local/share/ersatztv"
        #  - "/media/rshah17/Drive 1/Watchable_Media/:/media:ro"
        #tunarr:
        #image: chrisbenincasa/tunarr
    # Uncomment along with runtime below to enable HW accel
    # image: chrisbenincasa/tunarr:latest-nvidia
    #  container_name: tunarr
    #network_mode: service:tailscale
    # Uncomment if using the Nvidia container
    # runtime: nvidia
    # environment:
      # Replace this with your timezone to ensure accurate guide
      # data and scheduling.
      # - TZ=America/New_York
      # Uncomment if you'd like to adjust default config path
      # - TUNARR_DATABASE_PATH=/your/path/tunarr
      #  volumes:
      # Choose a path on your host to map to /config/tunarr. This ensures
      # that restarting the container will not delete your settings or DB.
      # - "/media/rshah17/Drive 1/tunarr/data:/config/tunarr"
    # The host path is relative to the location of the compose file
    # This can also use an absolute path.
    #
    # Uncomment if migrating from dizquetv. Chnage the host path
    # to the location of your dizquetv "database"
    # - ./.dizquetv:/.dizquetv
